### ISSUE TITLE
Resume 

### ISSUE THREAD

**Issue by GufranAnsari** [thibaultCha/TCBlobDownloadSwift#3]
How to Resume a download when application restart.

**Comment by thibaultcha** [comment]
To resume a download between application restarts, you should cancel an on-going download by calling `cancelWithResumeData`, store the return value somehow, and then pass it back to `downloadFileWithResumeData`.

See [cancelWithResumeData](https://github.com/thibaultCha/TCBlobDownloadSwift/blob/master/Source/TCBlobDownload.swift#L65)
and [downlaodFileWithResumeData](https://github.com/thibaultCha/TCBlobDownloadSwift/blob/master/Source/TCBlobDownloadManager.swift#L88)

**Comment by GufranAnsari** [comment]
thanks  bro

**Comment by thibaultcha** [comment]
yc, "bro".
