### ISSUE TITLE
No such module 'TCBlobDownloadSwift'

### ISSUE THREAD

**Issue by ylisr** [thibaultCha/TCBlobDownloadSwift#4]
Hi, I'm trying to import the source files into my project since I still need iOS 7 support, however Xcode can't find them. I've copied and pasted `TCBlobDownload.swift`, `TCBlobDownloadManager.swift`, and `TCBlobDownloadSwift.h` into my project.

The error is "No such Module 'TCBlobDownloadSwift'", when I put <code>import TCBlobDownloadSwift</code> on top of my downloading view controller. I've tried clean, re-open, delete stuff under derivedData folder, none is working. Does anyone have any idea how to fix it? Thanks!

**Comment by thibaultcha** [comment]
Is your project a Swift project?

**Comment by ylisr** [comment]
@thibaultCha Yes it's a Swift project with a few objC components. My bad, turns out there's no need to `import TCBlobDownloadSwift` if you've already added the source files to your project. Delete the row and everything works just fine.
The swift version is really beautifully written, now I can get rid a lot of redundant code.Thank you very much :)

**Comment by thibaultcha** [comment]
Great! And thank you!
