### ISSUE TITLE
Error while installing via pods

### ISSUE THREAD

**Issue by tarzon** [thibaultCha/TCBlobDownloadSwift#5]
This is the Error in TCBlobDownloadManager.swift file: Cannot invoke initializer for type 'TCBlobDownload' with an argument list of type '(downloadTask: NSURLSessionDownloadTask, toDirectory: NSURL?, fileName: NSString?, delegate: TCBlobDownloadDelegate?)'

![screen shot 2015-05-27 at 4 11 33 pm](https://cloud.githubusercontent.com/assets/2269630/7834321/afa53838-048b-11e5-9cc1-03606aec74ad.png)

**Comment by bonebox** [comment]
I'm seeing the same thing.  It looks like the project needs to be updated to support Swift 1.2.

**Comment by thibaultcha** [comment]
Mhh yes it was updated but I did not push a release on Cocoapods, sorry! I'll do it very soon

**Comment by bonebox** [comment]
Thanks, @thibaultCha!  In the meantime, it can still be used by putting this in the Podfile:

`pod 'TCBlobDownloadSwift', :git => 'https://github.com/thibaultCha/TCBlobDownloadSwift', :branch => 'master'`

**Comment by tarzon** [comment]
@bonebox  Thanks!!!

**Comment by thibaultcha** [comment]
I just updated the Cocoapods repo with version `0.1.0`! It has the major feature I want to be included but I'm waiting a bit more for it to turn 1.0. Anyways, I think we can close this now, and thanks for noticing!
