### ISSUE TITLE
TCBlobDownload--updating handlers/delegates

### ISSUE THREAD

**Issue by bonebox** [thibaultCha/TCBlobDownloadSwift#6]
In my app, the view that initiates file downloads using TCBlobDownload is a child view that can be dismissed/dealloc'd. TCBlobDownload continues downloading the files in the background, which is great. However, when the download view is closed and reopened, I lose access to the handlers/delegate, which I need in order to continue updating progress bars in the UI. Is there a way to do this, currently? I tried directly accessing both the `delegate` and `progression`/`completion` properties of `TCBlobDownload` in order to update them, but these aren't made public. It would be nice if these could either be made public, or provide a method to update them after the download has begun.

**Comment by bonebox** [comment]
FYI, I'm using a fork with these changes and it's working well.  Let me know if you want me to send a pull request.

**Comment by thibaultcha** [comment]
Yes I can see your point, a PR is welcomed!

**Comment by bonebox** [comment]
I submitted a PR for this, if you would like to merge it in.

**Comment by thibaultcha** [comment]
Sorry I did not have time to study this

**Comment by bonebox** [comment]
You merged this a while back https://github.com/thibaultCha/TCBlobDownloadSwift/pull/7, I just forgot to close it ;)

**Comment by thibaultcha** [comment]
Ohhh sorry I confused it with the other PR! Thanks!
